# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ice Framework
tagline:          ''
description:      'ice-framework is a starter platform for start building php and js based web applications'
url:              http://thilinah.github.com/ice-framework
baseurl:          /ice-framework/
baseurlnoslash:   /ice-framework

author:
  name:           'Thilina Hasantha'
  url:            https://twitter.com/thilina84
  image:		  http://graph.facebook.com/thilinah/picture?width=140&height=140

paginate:         5

# Custom vars
version:          2.1.0

social:
  twitter:        https://twitter.com/thilina84
  github:         https://github.com/thilinah
  linkedin:       http://lk.linkedin.com/in/thilinah
  facebook:        https://www.facebook.com/thilinah